export const languageMapping = {
  username: 'Tên đăng nhập',
  phone: 'Số điện thoại',
  fullName: 'Họ và tên',
  address: 'Địa chỉ',
  email: 'Email',
  password: 'Mật khẩu',
  personnelCode: 'Mã người dùng',
  passwordNew: 'Mật khẩu mới',
  passwordOld: 'Mật khẩu cũ',
  userId: 'ID người dùng',
  orgCode: 'Mã tổ chức',
  orgName: 'Tên tổ chức',
  startTime: 'Thời gian bắt đầu',
  endTime: 'Thời gian kết thúc',
  branchName: 'Tên chi nhánh',
  branchCode: 'Mã chi nhánh',
  branch: 'Chi nhánh',
  paymentPartner: 'Đối tác thanh toán',
  paymentMethod: 'Phương thức thanh toán',
  bankPaymentGateway: 'Ngân hàng thanh toán',
  TIDName: 'Tên TID',
  bankAccountNumber: 'Số tài khoản ngân hàng',
  note: 'Ghi chú',
  groupStudent: 'Nhóm học viên',
  typeFee: 'Loại học phí',
  partnerName: 'Tên đối tác',
  partnerCode: 'Mã đối tác',
  abbreviation: 'Tên viết tắt',
  taxCode: 'Mã số thuế',
  type: 'type',
  ruleType: 'ruleType',
  ruleConfig: 'ruleConfig',
  name: 'name',
  status: 'Trạng thái',
  _id: '_id',
  feePercent: 'feePercent',
  fixedCharge: 'fixedCharge',
  transactionChannel: 'Kênh giao dịch',
  paymentIntermediaries: 'Đối tác thanh toán',
  effectiveFromDate: 'Ngày hiệu lực',
  effectiveToDate: 'Ngày hết hiệu lực',
  createAtBy: 'Người tạo',
  createAtTime: 'Thời gian tạo',
  groupName: 'Tên nhóm',
  amount: 'Số tiền',
  clientCode: 'Mã khách hàng',
  schoolCode: 'Mã cơ sở đào tạo',
  schoolName: 'Tên cơ sở đào tạo',
  idSchool: 'ID cơ sở đào tạo',
  fax: 'Số fax',
  'must be an email': 'email không hợp lệ',
  'should not be empty': 'không được để trống',
  'must be an array': 'phải là mảng',
  'must be a string': 'phải là chuỗi',
  'should not contain special characters or spaces':
    'không được chứa ký tự đặc biệt hoặc khoảng trắng',
  'Số điện thoại không hợp lệ': 'Số điện thoại không hợp lệ',
  'must be a number conforming to the specified constraints': 'phải là số',
  'should not contain a   string': 'không được chứa khoảng trắng',
  'must be one of the following values: ONLYONE, ACTIVESTANDBY, COACTIVE, TIMEBASED, ':
    'phải là một trong các giá trị sau: ONLYONE, ACTIVESTANDBY, COACTIVE, TIMEBASED ',
};
